ko-build/ko

pkg/build/gobuild_test.go
Tests were depending on go-containerregistry packages being available and now they aren't.
=> Fix unit tests

Gopkg.lock, pkg/publish/daemon.go, pkg/publish/default.go, pkg/publish/default_test.go, pkg/publish/future_test.go, pkg/publish/options.go, pkg/resolve/fixed_test.go, pkg/resolve/resolve_test.go, vendor/github.com/google/go-containerregistry/pkg/name/check.go, vendor/github.com/google/go-containerregistry/pkg/name/digest.go, vendor/github.com/google/go-containerregistry/pkg/name/options.go, vendor/github.com/google/go-containerregistry/pkg/name/ref.go, vendor/github.com/google/go-containerregistry/pkg/name/registry.go, vendor/github.com/google/go-containerregistry/pkg/name/repository.go, vendor/github.com/google/go-containerregistry/pkg/name/tag.go, vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go
See https://github.com/google/go-containerregistry/pull/419 and https://github.com/google/go-containerregistry/pull/420
=> Drop name.WeakValidation

.gitignore, cmd/ko/commands.go, cmd/ko/debug.go, cmd/ko/publish.go, cmd/ko/resolve.go, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go
Add --disable-optimizations flag to make debugging easier. 
---
I used this, along with a different base image (`ubuntu:bionic-20190307`), so that I could interactively debug a `ko` built and applied container running in my Kubernetes cluster, using `squash` and VS Code.
=>  Add --disable-optimizations flag to make debugging easier.

cmd/ko/commands.go, cmd/ko/publish.go, cmd/ko/resolve.go, pkg/commands/options/binary.go, pkg/commands/options/debug.go, pkg/commands/options/filestuff.go, pkg/commands/options/flatname.go, pkg/commands/options/local.go, pkg/commands/options/tags.go
The options were all in the cmd dir. That's real weird. Moving these.
@jonjohnsonjr
=> Moving options to pkg/commands/options.

pkg/commands/commands.go, pkg/commands/create.go
I wanted `ko create -f config/file.yaml` 
but I had to `ko publish -f config/file.yaml | kubectl create -f -`
Fixed that by just adding `create` to `ko`.
=> Adding ko create

pkg/commands/apply.go, pkg/commands/config.go, pkg/commands/create.go, pkg/commands/publish.go, pkg/commands/publisher.go, pkg/commands/resolve.go, pkg/commands/resolver.go, pkg/commands/run.go
This hoists the publisher creation out of the loop for `ko publish` to
avoid needlessly resolving credentials multiple times.
This pulls the publisher creation outside of resolveFilesToWriter so we
can fail earlier if e.g. KO_DOCKER_REPO is unset, otherwise we start up
the kubectl goroutine and it would asynchronously fail with:
error: no objects passed to apply
=> Return better error messages

pkg/commands/publish.go
This will allow us to use it in a build script that isn't geared towards k8s, by naming packages we intend to publish directly, and then using the stdout to understand what images we published.
It's much easier than `... 2>&1 | grep -E '(Loaded|Published)' | rev | cut -d ' ' -f 1 | rev`
=> Print images to stdout as we publish them

pkg/build/gobuild.go
Fixes #42
We might not want to embed the import path, since that isn't really content-addressable, but we might already be embedding that somewhere? Not sure...
```
$ crane config $(ko publish github.com/google/ko/cmd/ko 2>/dev/null) | jq .
{
"architecture": "amd64",
"author": "github.com/google/ko",
"created": "1970-01-01T00:00:00Z",
"history": [
{
"author": "Bazel",
"created": "1970-01-01T00:00:00Z",
"created_by": "bazel build ..."
},
{
"author": "ko",
"created": "0001-01-01T00:00:00Z",
"created_by": "ko publish github.com/google/ko/cmd/ko",
"comment": "kodata contents, at $KO_DATA_PATH"
},
{
"author": "ko",
"created": "0001-01-01T00:00:00Z",
"created_by": "ko publish github.com/google/ko/cmd/ko",
"comment": "go build output, at /ko-app/ko"
}
],
"os": "linux",
"rootfs": {
"type": …
```
=> Add author and created_by data

pkg/build/gobuild.go
Changing the order of environment variables so that user supplied value for `CGO_ENABLED` take priority 
https://github.com/google/ko/issues/52
=> support user ability to overwrite CGO_ENABLED environment variable

pkg/commands/options/local.go, pkg/commands/resolver.go, pkg/publish/default.go, pkg/publish/options.go
Why this is necessary: when using a local docker registry, users may not
want to support https, or there may be other troubles not allowing
verifiable TLS support.
This commit adds this functionality by adding an `--insecure-registry`
flag.
@jonjohnsonjr 
Fixes #64
=> Allow skipping TLS verification while publishing image

pkg/build/gobuild.go, pkg/build/gobuild_test.go
I suspect that this may be a source of problems reading kodata with nonroot,
but it is probably worth doing either way.
=> Add permissions to the kodata directory.

README.md
Describe `SOURCE_DATE_EPOCH` in the readme.
=> Add SOURCE_DATE_EPOCH usage

pkg/build/gobuild.go, pkg/build/gobuild_test.go
=> Use GOOS/GOARCH from base image

pkg/commands/resolver.go, pkg/publish/options.go
This allows you to use e.g. localhost:5000 as KO_DOCKER_REPO.
Fixes #93.
=> Allow plain registries as KO_DOCKER_REPO

pkg/commands/resolver_test.go, pkg/resolve/selector.go, pkg/resolve/selector_test.go
Resolving a YAML that ends in an empty YAML node.
```shell
go run ./cmd/ko resolve -l foo=bar -f - <<END
apiVersion: v1
kind: A
metadata:
labels:
foo: bar
---
END
```
Before this change:
```
error processing import paths in "-": error evaluating selector: yaml doesn't represent a k8s object
exit status 1
```
After this change:
```
apiVersion: v1
kind: A
metadata:
labels:
foo: bar
---
```
=> Ignore null YAML documents when using a label selector.

pkg/publish/default.go, pkg/publish/default_test.go
If a single tag is explicitly set (i.e. it's not "latest"), include that
in the reference that gets rendered in the yaml.
This is really useful for tracking releases.
Fixes https://github.com/google/ko/issues/108
Also fixes a TODO.
=> Include tag in resolved references

pkg/build/gobuild.go, pkg/build/gobuild_test.go
Since we are always building linux containers, use `path.Join` rather than `filepath.Join` when adding files to the tar.
Verified by building https://github.com/knative/serving and https://github.com/knative/serving-operator and installing in a cluster.
=> Fix path mangling on Windows.

pkg/commands/run.go
Shift the UX closer to `go run` than `kubectl run`.
This also adds some flags to make `ko run` spin up a pod, attach logs, and automatically clean itself up.
This drops the ability to override kubectl flags, but if you're going to do that I'd say just use some yaml 🤷‍♂.
Edit: Matt pointed out that you can just do `kubectl run --name=$(ko publish IMPORTPATH)` if you want to control flags, which is really nice. I'm happy with keeping `ko run` as just easy defaults.
Fixes https://github.com/google/ko/issues/5
```
$ ko run ./cmd/ko -- run -h
2019/08/16 11:25:06 Building github.com/google/ko/cmd/ko
2019/08/16 11:25:12 Using base gcr.io/distroless/static:latest for github.com/google/ko/cmd/ko
2019/08/16 11:25:13 Publishing gcr.io/jonjohnson-test/ko/ko-099ba5bcefdead87f92606265fb99ac0:latest …
```
=> Improve `ko run`

pkg/build/gobuild.go, pkg/build/gobuild_test.go
This makes it easier to invoke the binary when using a debug container.
E.g. you could invoke `ko` instead of `/ko-app/ko`.
=> Add entrypoint to PATH

pkg/publish/options.go
Fixes #93
With this change we support also pointing to default registry (without prefix).
Eg. KO_DOCKER_REPO=myuser
=> Reorder parsing KO_DOCKER_REPO to get proper credentials

pkg/commands/apply.go, pkg/commands/commands.go, pkg/commands/create.go, pkg/commands/delete.go
This pull request adds an error message in case `kubectl` is not installed. I'm assuming most users of `ko` will have `kubectl` installed, but it's nice to have a clear message in the edge case when it's not available.
=> Add kubectl Check for ko delete

README.md
https://github.com/google/ko/blob/ImJasonH-patch-1/README.md#strict-mode
=> Document strict mode in README.md

pkg/build/gobuild.go, pkg/build/gobuild_test.go
Fixes the PATH environment variable so it contains the directory
containing the binary (i.e., /ko-app) instead of the binary itself
(e.g., /ko-app/ko).
See #114.
=> Fix: Add directory containing binary to PATH

pkg/commands/config.go
This allows viper configuration to be set using environment variables
instead of just with a config file.
Fixes #130 
```
$ KO_DEFAULTBASEIMAGE=ubuntu ko publish ./cmd/ko
2020/02/06 13:31:51 Using base ubuntu for github.com/google/ko/cmd/ko
```
```
$ KO_BASEIMAGEOVERRIDES='{"github.com/google/ko/cmd/ko":"ubuntu"}' ko publish ./cmd/ko
2020/02/06 13:30:08 Using base ubuntu for github.com/google/ko/cmd/ko
```
=> Set AutomaticEnv for viper

pkg/commands/apply.go, pkg/commands/create.go, pkg/commands/resolve.go, pkg/commands/resolver.go
Fixes #84 
When resolving files, we would just log.Fatal if we encountered an
error. This seems to be racy and causes ko to exit with a 0 error code
when it shouldn't. To fix this, we synchronize the builder goroutines
with the kubectl go routine and exit with an error if either of them
failed.
This fix also happened to fix a goroutine leak. If the kubectl goroutine
failed, we never properly cancelled the builds, which would happily
conitnue compiling packages and consuming resources.
=> Deterministically fail ko {apply, create}

pkg/build/gobuild.go, pkg/commands/config.go
This fixes an issue where import paths with uppercase (github.com/GoogleCloudPlatform :eyes:) were being canonicalized by Viper to all lowercase and the baseImageOverrides in `.ko.yaml` were failing to properly identify the base image.
I hit this in: https://github.com/tektoncd/pipeline/pull/2435 trying to opt some of the GCP images out of `:nonroot`.
This also adds some logging to a place where I see a lot of folks have issues with `ko` where we swallow an error.  I hit it experimenting with variants on the `ko publish` import path, and added the logging to debug.
=> Viper keys are case insensitive.

pkg/build/gobuild.go, pkg/build/strict.go, pkg/build/strict_test.go, pkg/internal/testing/fixed.go, pkg/resolve/resolve.go, pkg/resolve/resolve_test.go
This change more or less completely changes how `ko://` is handled internally to `ko`, but the user-facing changes should only be net-positive.  `ko://` was previously stripped at the highest level, and the build logic was unaware, which had some undesirable diagnostic/functional implications that are collectively addressed in this change.
With this change, the `ko://` prefix is preserved and passed to the build logic, which internally parses a new `reference` type (this was useful to have Go's type checker find all of the places that needed fixing).  The main functional differences are:
1. If a reference is prefixed with `ko://` we will now fail fast in `IsSupportedReference` regardless of whether `--strict` is passed.
2. If a reference is prefixed with `ko://` it will bypass the prefix …
=> Refactor how/where ko:// is handled.

pkg/publish/default.go, pkg/publish/default_test.go
Turns out I broke this.  Thanks to @bobcatfish for reporting the issue.
With this change:
```
ko resolve -Pf cmd/ko/test/test.yaml > /dev/null
2020/05/04 08:44:35 Using base gcr.io/distroless/static:nonroot for github.com/google/ko/cmd/ko/test
2020/05/04 08:44:36 Building github.com/google/ko/cmd/ko/test
2020/05/04 08:44:37 Publishing gcr.io/mattmoor-knative/github.com/google/ko/cmd/ko/test:latest
2020/05/04 08:44:39 Published gcr.io/mattmoor-knative/github.com/google/ko/cmd/ko/test@sha256:ee655510172b429dbce619fc69677621d71cb824cbbf2a21746d700127257ec4
```
I can cut v0.5.1 once this lands.
=> Fix -P with passing ko:// through.

cmd/ko/test/main.go, pkg/build/gobuild_test.go, pkg/commands/config.go, pkg/resolve/resolve_test.go
Well, as per title. Properly key struct literals, don't use formatting functions where not necessary and convert from buffer to string directly.
=> Some small nits around the codebase to make linters happy.

pkg/publish/tarball.go
As per title, a little bit of hygiene.
=> Make Tarball publisher types private and return Interface.

go.mod, vendor/modules.txt
The "require" is behind the version in "replace", and since cli-runtime references the package mentioned in the errors we are seeing, rule this out as a source!
=> Fix k8s.io/cli-runtime "require"

README.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/commands/config.go
For after we cut a release.
Fixes: https://github.com/google/ko/issues/158
Fixes: https://github.com/google/ko/issues/160
=> Remove deprecated things.

.codecov.yaml, .golangci.yaml, hack/boilerplate/boilerplate.go.txt, hack/boilerplate/boilerplate.sh.txt
`.codecov.yaml` - Enable codecov.io coverage reports
`.golangci.yaml` - Enable the enumerated checks in golangci-lint
`boilerplate.*.txt` - Enable file header boilerplate checks for these extensions
=> Add a handful of files to trigger more analyses.

pkg/commands/config.go
I noticed that my `.ko.yaml` was being ignored because it was looking for `ko://` prefixed things.
I also tried this with `ko publish` three ways: `ko://`-prefixed, non-`ko://` prefixed, and relative path, and all picked up the appropriate base.
=> Fix base image resolution

cmd/ko/main.go, pkg/commands/config.go
These got dropped when we pulled in:
https://github.com/google/go-containerregistry/pull/481
Which doesn't log by default, and requires opting in.
Before:
```
$ ko publish -P ./cmd/ko/
2020/09/25 11:23:47 Using base gcr.io/distroless/static:nonroot for ko://github.com/google/ko/cmd/ko
2020/09/25 11:23:48 Building github.com/google/ko/cmd/ko for linux/amd64
2020/09/25 11:23:56 Publishing gcr.io/jonjohnson-test/ko/github.com/google/ko/cmd/ko:latest
2020/09/25 11:24:10 Published gcr.io/jonjohnson-test/ko/github.com/google/ko/cmd/ko@sha256:088f55132ffdea808364a21f9973b9e463c03b9bc1f8a33a80bbaa89a359f456
gcr.io/jonjohnson-test/ko/github.com/google/ko/cmd/ko@sha256:088f55132ffdea808364a21f9973b9e463c03b9bc1f8a33a80bbaa89a359f456
```
After:
```
$ ko publish -P ./cmd/ko/
2020/09/25 11:23:08 Using …
```
=> Revive progress and warning logs

README.md
KO gives an error for the wrong go versions. The error is not very verbose.It is diffcult to decipher the logs of the error given. As a developer, adding a note to the installation process would prevent me from stumbling onto this issue.
=> (Fix #191) Add required go version to docs

integration_test.sh, pkg/publish/kind.go
Fix --platform=all with kind.local
=> Have kind.local test use --platform=all

README.md, pkg/commands/apply.go, pkg/commands/create.go, pkg/commands/options/strict.go, pkg/commands/resolve.go
#162 removed support for `--strict` without removing docs describing the flag, or the now-meaningless flag.
=> Remove docs for Strict Mode and --strict flag

pkg/commands/resolver.go, pkg/publish/multi.go, pkg/publish/multi_test.go
=> Don't panic when MultiPublisher is given zero publishers

README.md
=> Document `--platform` flag in README.md

.github/workflows/knative-boilerplate.yaml, .github/workflows/knative-go-test.yaml, .github/workflows/knative-security.yaml, .github/workflows/knative-style.yaml, .github/workflows/knative-verify.yaml
Produced via:
```shell
cp $(find "${GITHUB_WORKSPACE}/meta/workflow-templates" -type f -name '*.yaml') \
"${GITHUB_WORKSPACE}/main/.github/workflows/"
```
/cc @jonjohnsonjr @ImJasonH
/assign @jonjohnsonjr @ImJasonH
=> [Automated] Update actions

pkg/build/build.go, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/limit.go, pkg/build/limit_test.go, pkg/build/recorder.go, pkg/build/recorder_test.go, pkg/build/shared.go, pkg/build/shared_test.go, pkg/commands/publisher.go, pkg/internal/testing/fixed.go, pkg/internal/testing/fixed_test.go, pkg/resolve/resolve.go
This can be useful to determine what they need to do to make a ko
publish work.
=> IsSupportedReference returns descriptive error

pkg/commands/options/publish.go, pkg/commands/resolver.go, pkg/publish/daemon.go, pkg/publish/daemon_test.go, pkg/publish/default.go, pkg/publish/default_test.go, pkg/publish/kind.go, pkg/publish/tarball.go, pkg/publish/tarball_test.go
In some environments (e.g. ECR) each repository needs to be pre-created, which gets tedious.
Given that `ko` does everything by digest, this collapses all of the images published into the same repository: `${KO_DOCKER_REPO}` with no suffix to discriminate between images.
This is also beneficial from a security standpoint in certain contexts, as `KO_DOCKER_REPO=docker.io/{user}` might publish new repositories as public by default.
=> Refactor the publish.Namer, add `--bare` option for image naming

pkg/build/gobuild.go, pkg/build/gobuild_test.go
This relies on some hard-coded knowledge of the go compiler, which is
unfortunate, so we will have to update this if things change.
Fixes https://github.com/google/ko/issues/235
```
$ crane manifest $(ko publish --platform=all -B ./cmd/ko) | jq .
2020/11/04 11:23:19 Using base golang for github.com/google/ko/cmd/ko
2020/11/04 11:23:19 No matching credentials were found, falling back on anonymous
2020/11/04 11:23:20 Building github.com/google/ko/cmd/ko for linux/amd64
2020/11/04 11:23:26 Building github.com/google/ko/cmd/ko for linux/arm
2020/11/04 11:24:38 Building github.com/google/ko/cmd/ko for linux/arm
2020/11/04 11:25:56 Building github.com/google/ko/cmd/ko for linux/arm64
2020/11/04 11:27:10 Building github.com/google/ko/cmd/ko for linux/386
2020/11/04 11:28:31 Building …
```
=> Set GOARM based on platform.variant

README.md, pkg/commands/apply.go, pkg/commands/create.go, pkg/commands/options/strict.go, pkg/commands/resolve.go
This reverts commit d7b989a9dffe912e3b4effa427628ebe08a40902.
Note this is for the release-0.6 branch. Will tag as v0.6.2 after this merges.
=> [release 0.6] Revert "Remove docs for Strict Mode and --strict flag (#210)"

README.md, cmd/ko/main.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/append.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/auth.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/blob.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/catalog.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/config.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/copy.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/delete.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/digest.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/export.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/list.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/manifest.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/pull.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/push.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/rebase.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/root.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/tag.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/validate.go, vendor/github.com/google/go-containerregistry/cmd/crane/cmd/version.go, vendor/github.com/google/go-containerregistry/pkg/v1/cache/cache.go, vendor/github.com/google/go-containerregistry/pkg/v1/cache/fs.go, vendor/github.com/google/go-containerregistry/pkg/v1/cache/ro.go, vendor/github.com/google/go-containerregistry/pkg/v1/validate/doc.go, vendor/github.com/google/go-containerregistry/pkg/v1/validate/image.go, vendor/github.com/google/go-containerregistry/pkg/v1/validate/index.go, vendor/github.com/google/go-containerregistry/pkg/v1/validate/layer.go, vendor/modules.txt
Fixes https://github.com/google/ko/issues/155
/assign @jonjohnsonjr @mattmoor
=> Add crane's auth command to facilitate logging into a registry

pkg/build/gobuild.go
```
$ crane manifest alpine | jq .
```
```json
{
"manifests": [
{
"digest": "sha256:d7342993700f8cd7aba8496c2d0e57be0666e80b4c441925fc6f9361fa81d10e",
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"platform": {
"architecture": "amd64",
"os": "linux"
},
"size": 528
},
{
"digest": "sha256:c4f0f03cda416f3e4cfebcfea9910463121651b019c6677053ece71084699f47",
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"platform": {
"architecture": "arm",
"os": "linux",
"variant": "v6"
},
"size": 528
},
{
"digest": "sha256:d0f78a6ddf7a457dc72dbd44eab67209454ddb1e6d2323fa8e27275bc13dc320",
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"platform": {
"architecture": "arm",
"os": "linux",
"variant": "v7"
},
"size": 528
},
{
"digest": …
```
=> Print variant from builder

README.md
I believe it should without docker, right? Using ko without ko sounds wrong.
=> documentation: auth without docker, not without ko

pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/commands/apply.go, pkg/commands/config.go, pkg/commands/create.go, pkg/commands/delete.go, pkg/commands/publish.go, pkg/commands/publisher.go, pkg/commands/resolve.go, pkg/commands/resolver.go, pkg/commands/run.go, pkg/internal/testing/fixed.go, pkg/internal/testing/fixed_test.go, pkg/publish/daemon.go, pkg/publish/daemon_test.go, pkg/publish/default.go, pkg/publish/default_test.go, pkg/publish/kind.go, pkg/publish/layout.go, pkg/publish/layout_test.go, pkg/publish/multi.go, pkg/publish/multi_test.go, pkg/publish/publish.go, pkg/publish/shared.go, pkg/publish/shared_test.go, pkg/publish/tarball.go, pkg/publish/tarball_test.go, pkg/resolve/resolve.go
I noticed that hitting ctrl-C didn't work when pushing images, this should fix that.
=> Add ctx everywhere

pkg/resolve/resolve.go
We were just throwing away the error for `ko resolve`.
Follow-up to https://github.com/google/ko/pull/233
=> Actually print errors during resolve

.travis.yml, README.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/config.go, pkg/commands/options/build.go, pkg/commands/resolver.go
Fixes https://github.com/google/ko/issues/253
Fixes https://github.com/google/ko/issues/274
```
$ ko publish -B --platform=linux/amd64,linux/arm64 ./cmd/ko/
2020/12/07 13:57:20 Using base gcr.io/distroless/static:nonroot for github.com/google/ko/cmd/ko
2020/12/07 13:57:21 Building github.com/google/ko/cmd/ko for linux/amd64
2020/12/07 13:57:25 Building github.com/google/ko/cmd/ko for linux/arm64
2020/12/07 13:57:29 Publishing gcr.io/jonjohnson-test/ko/ko:latest
2020/12/07 13:57:30 existing blob: sha256:72164b581b02b1eb297b403bcc8fc1bfa245cb52e103a3a525a0835a58ff58e2
2020/12/07 13:57:30 existing blob: sha256:e59bd8947ac7af2c8f4403b183326986ab554bbc262739cf5d9d596c7c7a3aca
2020/12/07 13:57:31 pushed blob: sha256:314bd22f324d73c81d23dd94a14e3a4df6a591381e39b9164163208115c23ae4
2020/12/07 …
```
=> Allow comma-separated list of platforms

README.md, cmd/ko/main.go
Fixes https://github.com/google/ko/issues/155
This was previously `ko auth login`, which I've hidden, and perhaps we
can alias to `ko login` in the future, but in theory folks could have
been using `ko auth get`, and I don't want to break that for no reason.
=> Add ko login

README.md
Fixes https://github.com/google/ko/issues/167
=> Document GOFLAGS

README.md
As suggested in Slack conversations install instructions should point to releases. So, make it so.
Fixes: #287
=> point to releases for installation

pkg/commands/config.go, pkg/commands/resolver.go, pkg/publish/default.go, pkg/publish/options.go
This was using remote.WithTransport to set it manually, and this is much
simpler (also annotates with the go-containerregistry version). This is
really nice because it will give us at least some version information
where we had none before (for non-releases).
Before:
ko
ko/(devel)
ko/v0.7.0
After:
ko go-containerregistry/v0.4.0
ko/(devel) go-containerregistry/v0.4.0
ko/v0.7.0 go-containerregistry/v0.4.0
=> Use remote.WithUserAgent where possible

main.go
This was missed when main.go was moved to the root.
=> Fix ko login

main.go
This was missed when main.go was moved to the root.
=> Cherry-pick #298

README.md
relates to #296
```
==> Downloading https://homebrew.bintray.com/bottles/ko-0.7.2.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/16cd2e751b78b91bd6e65b8b396afbfad8ce211942adf9eb4b602c25e8a5b9df?response
######################################################################## 100.0%
==> Pouring ko-0.7.2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/ko/0.7.2: 5 files, 35.4MB
```
=> doc: add homebrew install

pkg/build/gobuild.go
Print a warning if GOROOT is unset and ko's default build context
differs from $(go env GOROOT) and use the result of $(go env GOROOT).
Fixes https://github.com/google/ko/issues/106
=> Fix GOROOT mismatch issues

.goreleaser.yml, .travis.yml
I am going to submit mips64le architecture，The main reasons are:
1、The mips64le architecture is also the mainstream cpu architecture (amd64, arm64), which is used by many users;
2、Golang supports cross compilation, and mips64le is officially supported;
Therefore, I hope that the release package also supports the mips64le architecture, which is convenient for more users.
=> support mips64le architecture.

pkg/build/gobuild.go
Fixes https://github.com/google/ko/issues/319
This is untested. The new `io/fs` stuff might make this easier, but I'm too lazy to try it out.
@benmoss would this have helped?
=> Wrap io errs for kodata layer

README.md
[Rendered](https://github.com/imjasonh/ko/blob/readme/README.md)
Recent feedback ([1](https://twitter.com/thomrstrom/status/1364028929514696704), [2](https://twitter.com/patricknflynn/status/1364213599426785289)) indicate that it's not clear enough that `ko` is a useful option for simply building container images, separate from its Kubernetes support.
This reorders README.md to start with installation options, then highlight `ko publish` first, then sidetrack into configuration options, then mention Kubernetes support (`ko resolve` -> `ko apply` -> `ko delete`), and end with an FAQ.
It's about 60% as many lines and half as many characters as the current README.
=> Streamline README.md

pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/options/build.go, pkg/commands/resolver.go
=> Add --image-label to add labels to built images

pkg/commands/options/publish.go
The current `--bare` help message is a little bit confusing: It says
that it will not work with `--tags` properly, but in fact, I would
assume it means that it may not work properly instead.
With `--bare`, the name will be `${KO_DOCKER_REPO}:<tag>`.
=> options: update --bare help message

.goreleaser.yml
Added ppc64le target as it was already in travis.yml but not in the build instructions for goreleaser
=> Added IBM Power support (ppc64le)

pkg/commands/apply.go, pkg/commands/create.go, pkg/commands/delete.go, pkg/commands/publish.go, pkg/commands/resolve.go, pkg/commands/run.go
Notably, this makes `ko` exit 1 when `kubectl` isn't installed, instead of logging and otherwise doing nothing.
Less notably, this makes the error from `ko run` slightly less verbose.
Otherwise no functional changes are expected.
=> Use cobra's RunE wherever possible

.goreleaser.yml
Also explicitly build for macOS (darwin), I'm not sure how that was being done before.
=> Build ko for Windows

README.md
Updating README with information on how to use openshift internal registry with ko.
=> Update README.md with information about openshift-registry

action.yml
Example usage:
```yaml
name: Publish
on:
push:
branches: [ 'main' ]
jobs:
publish:
name: Publish
steps:
- uses: actions/setup-go@v2
with:
go-version: 1.15
- uses: actions/checkout@v2
- name: Setup ko
uses: google/ko@main
- name: Publish
run: ko publish ./cmd/server
```
This workflow will install the latest released version of `ko` by default, `ko login ghcr.io` using the [`GITHUB_TOKEN` secret](https://docs.github.com/en/actions/reference/authentication-in-a-workflow), and set `KO_DOCKER_REPO=ghcr.io/[owner]/[repo]` for future steps, so the `ko publish` step will publish to `ghcr.io/[owner]/[repo]/server-[md5]`.
If a user wants to publish elsewhere, they can set `KO_DOCKER_REPO` themselves and provide credentials for that registry.
The action takes an input to install a specific version …
=> Add GitHub Action to install and setup ko

README.md, pkg/commands/options/publish.go, pkg/commands/resolver.go
This enables programmatically setting the destination image repository
when embedding ko's `publish` functionality in other tools.
See discussion in https://github.com/google/ko/pull/348 for additional context.
=> Add flag and PublishOption for destination repo

pkg/commands/options/publish.go, pkg/commands/resolver.go, pkg/publish/daemon.go, pkg/publish/daemon_test.go
Add a `LocalDomain` field to `PublishOptions`, but no flag (yet?).
This allows use of a domain (base repo) other than `ko.local` for images
that are side-loaded to the local Docker daemon.
An alternative implementation would be to add a boolean field that
indicates that `ko publish` should use the value of the `KO_DOCKER_REPO`
environment variable (or the `DockerRepo` field in `PublishOptions`) as
the base name for images side-loaded to the local Docker daemon. I'd be
happy to get feedback on which option would work best.
=> Enable override of daemon publisher local domain

pkg/commands/options/publish.go, pkg/commands/resolver.go, pkg/publish/default.go, pkg/publish/default_test.go, pkg/publish/options.go
The `--tag-only` flag resolves images into tag-only references. This flag is useful when digests are not preserved when images are repopulated. It can only be used when a single tag is specified, and the tag is not `latest`.
=> Add a tag-only flag to publisher.

pkg/commands/config.go, pkg/commands/config_test.go, pkg/commands/options/build.go, pkg/commands/options/publish.go, pkg/commands/publisher.go, pkg/commands/publisher_test.go, pkg/commands/resolver.go, pkg/commands/resolver_test.go
Enable embedding of ko's `publish` functionality to be in other tools.
- Export `MakeBuilder()`, `MakePublisher()` and `PublishImages()` from `pkg/commands`
- Allow overriding `UserAgent()`
- Add `DockerRepo` flag to `PublishOptions` in `pkg/commands/options`
See https://github.com/GoogleContainerTools/skaffold/pull/5611
=> Enable embedding of ko publish

pkg/commands/apply.go, pkg/commands/config.go, pkg/commands/create.go, pkg/commands/options/build.go, pkg/commands/publish.go, pkg/commands/resolve.go, pkg/commands/run.go
Fixes https://github.com/google/ko/issues/369
=> Propagate --insecure-registry to base image

README.md, pkg/commands/config.go
Fixes https://github.com/google/ko/issues/368
=> Look for ko.local in the daemon

README.md
I think this got dropped in the great README rewrite of 2021.
=> Document KIND_CLUSTER_NAME env var in README.md

README.md, pkg/build/gobuild.go, pkg/build/options.go, pkg/commands/config.go, pkg/commands/resolver.go
Example:
```sh
export KO_DATA_DATE_EPOCH=$(git log -1 --format='%ct')
ko publish .
```
This allows static file servers mounted at `KO_DATA_PATH` to send the `Last-Modified` header and handle revalidation requests.
=> Add KO_DATA_DATE_EPOCH env var to set the modification time for files in `kodata`

README.md, pkg/build/config.go, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/config.go, pkg/commands/config_test.go, pkg/commands/resolver.go
Fixes #316
There are use cases, where multiple Go build flags need to be set. However, the environment variable to pass flags to Go build has some limits for `ldFlags`.
Proposed changes:
- Add GoReleaser inspired configuration section to `.ko.yaml` to support setting specific Go build and ldFlags to be used by the build.
- Add support for environment variables `KO_GOBUILD_FLAGS` to add extra build flags and `KO_GOBUILD_LDFLAGS` to add extra ldFlags.
=> Add support for Go build flags

pkg/commands/options/publish.go, pkg/commands/resolver.go, pkg/commands/resolver_test.go, pkg/publish/daemon.go, pkg/publish/daemon_test.go
When embedding ko, it may be necessary to override the docker client.
This adds a PublishOption to inject a docker client created elsewhere.
Ko will use this client to interact with the docker daemon.
Context: https://github.com/GoogleContainerTools/skaffold/pull/6054#discussion_r662230195
=> Enable overriding docker client

pkg/publish/layout_test.go, pkg/publish/multi_test.go
Fixes https://github.com/google/ko/issues/256
The default temp dir on macos is something like `/var/folders/bb/l0yfqc6d6kb5zm5f9ktyx0nw0000gn/T/ko299660247`, which  results in error messages like:
```
layout_test.go:45: Publish() = repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: /var/folders/bb/l0yfqc6d6kb5zm5f9ktyx0nw0000gn/T/ko299660247
```
By forcing the temp dir into `/tmp`, we make sure we generate a valid repository.
=> Fix layout tests on macos

main.go
See https://github.com/spf13/cobra/issues/340 for why this isn't the default (answer: historically, it wasn't the default, and spf13 is trying not to break people).
=> Silence usage report on internal errors

README.md
I got the following error when following the original instructions:
go install: version is required when current directory is not in a module
Try 'go install github.com/google/ko@latest' to install the latest version
=> Update "go install" instructions

pkg/publish/options.go
Fixes #396
Note that this is technically breaking if people are using --insecure-registry and replacing the RoundTripper with something that's not an `http.Transport`. I decided to blow up loudly, rather than let it pass, but I could be convinced to go the other way.
Verified on harbor 2.2.3 with a self-signed cert with a SAN of 192.168.10.12.
=> Make --insecure-registry work with TLS registries whose certs we can't verify.

pkg/build/gobuild.go
https://github.com/tektoncd/pipeline/issues/1826#issuecomment-883095905 says the suffix isn't necessary, and having different entrypoint locations makes some of Tekton's usage more complicated.
=> Don't add .exe suffix to windows executables

pkg/build/gobuild.go, pkg/build/gobuild_test.go
Based on conversation in https://github.com/google/go-containerregistry/pull/1098
=> Don't set image.base.name if base is specified by digest

hack/presubmit.sh
spf13/cobra inserts comments with dates in generated Markdown files.
This change makes the presubmit check ignore those comments when verifying that ko's Markdown docs are up-to-date.
Also fixes some `shellcheck` warnings.
=> Ignore cobra auto-generated comments with dates in doc diff

README.md, pkg/build/config.go, pkg/build/gobuild.go, pkg/build/gobuild_test.go
Matches the GoReleaser format.
Related: #340
=> Enable setting environment variables in .ko.yaml

.github/workflows/modules-integration-test.yaml, go.mod, integration_test.sh
Go 1.16 introduces "embed", which folks are starting to adopt.
Folks are also starting to use things from `io` instead of `ioutil`, which is another 1.16 change I've seen folks picking up without even realizing it.
=> Bump to Go 1.16.x

README.md
* Update the OpenShift documentation url to use latest instead of a specific version.
* Use `openshift registry info --public` to get registry public URL
=> Update OpenShift instructions to point to latest

.github/workflows/boilerplate.yaml, .github/workflows/build.yaml, .github/workflows/e2e.yaml, .github/workflows/kind-e2e.yaml, .github/workflows/modules-integration-test.yaml, .github/workflows/release.yml, .github/workflows/style.yaml, .github/workflows/test.yaml, .github/workflows/verify.yaml, hack/tools.go
- module integration test now runs with 1.16 and 1.17, and drops an unnecessary `matrix` value.
- drop unnecessary step `name`s (e.g., "Set up Go 1.17.x", which is redundant with the step config, and will only fall out of date and confuse people), and `shell:bash` (`bash` is the default value)
=> [ci] upgrade to Go 1.17 everywhere, clean up configs

pkg/build/gobuild.go, pkg/build/gobuild_test.go
Platform resolution unit tests were affected by GOARCH/GOOS. Move the
os.Environ() call out of the function under test to avoid this.
Fixes https://github.com/google/ko/issues/454
=> Isolate unit tests from os.Environ

.github/workflows/analyze.yaml
These were dropped in https://github.com/google/ko/pull/364 and I don't remember why. The result is that code scanning alerts have been disabled since May: https://github.com/google/ko/security/code-scanning
=> Re-enable codeql analysis

pkg/build/gobuild.go, pkg/build/gobuild_test.go
Followup from #354 
Before this change, if the base image was a Docker manifest list, it could not be annotated with base image information. With this change, `ko` always produces OCI images and indexes, which can be annotated.
Verified manually as well:
```
$ crane manifest $(go run ./ publish ./test --platform=all) | jq '.annotations'
...
{
"org.opencontainers.image.base.digest": "sha256:7cb5539ebb7b99352d736ed97668060cee123285f01705b910891acdf7d945e3",
"org.opencontainers.image.base.name": "gcr.io/distroless/static:nonroot"
}                                                                                                                                                      
```
=> Always produce OCI images and indexes

pkg/build/gobuild.go, pkg/build/gobuild_test.go
This reverts commit 465eca2b93f860b212a2911f93dc9547876f898a. (#449)
This breaks pushing to quay.io.
=> Revert "Always produce OCI images and indexes (#449)"

main.go, pkg/commands/apply.go, pkg/commands/build.go, pkg/commands/config.go, pkg/commands/create.go, pkg/commands/delete.go, pkg/commands/deps.go, pkg/commands/resolve.go, pkg/commands/run.go
=> Use signal.NotifyContext

.github/workflows/e2e.yaml, .ko.yaml, test/main.go
This tests and demonstrates using ldflags in a `.ko.yaml` file to set a variable value at build-time.
=> Add e2e test for using ldflags to set a build-time variable

pkg/commands/create.go
I think this use of `kubectl create` was accidentally replaced by `kubectl apply` (assumption based on the fact that the comments and error messages surrounding this change weren't updated to reflect new use of `apply`).
We've started seeing errors from `ko` in Tekton Pipelines' integration test runs with the following format today, which I believe are related:
```
error: from default-cluster-admin-: cannot use generate name with apply
Error: error executing 'kubectl create': exit status 1
2021/11/09 16:40:53 error during command execution:error executing 'kubectl create': exit status 1
```
=> Fix issue where kubectl apply is run in place of kubectl create

pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/options/build.go, pkg/commands/options/build_test.go, pkg/commands/resolver.go
Enables programmatic control of adding the `-trimpath` flag to `go build`.
The `-trimpath` flag removes file system paths from the resulting binary. `ko` adds `-trimpath` by default as it aids in achieving reproducible builds.
However, removing file system paths makes interactive debugging more challenging, in particular in mapping source file locations in the IDE to debug information in the binary.
If you set `Trimpath` to `false` to enable interactive debugging, you likely also want to set `DisableOptimizations` to `true` to disable compiler optimizations and inlining.
Reference for `-trimpath`: https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies
Resolves: #500
Related: #71, #78, https://github.com/GoogleContainerTools/skaffold/issues/6843
=> Add `Trimpath` build option

.github/workflows/kind-e2e.yaml, doc/ko_apply.md, doc/ko_build.md, doc/ko_create.md, doc/ko_deps.md, doc/ko_resolve.md, doc/ko_run.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/deps.go, pkg/commands/options/build.go, pkg/commands/resolver.go
This combines Jason's SPDX stuff and my SBOM stuff to support
SPDX-based SBOMs by default instead of our `go version -m`
invention.
To simplify things, I got rid of `disableSBOM` in favor of supporting
`nil` and simply eliding the SBOM call.
=> Connect SBOMs with SPDX support.

internal/sbom/spdx.go, pkg/commands/resolver.go
We were emitting package checksum hashes as `h1:{base64}`.  `h1:` is a prefix that indicates "Hash 1", which is a SHA-256 based hash of the files, which is then base64 encoded as the suffix.
This change detects/strips the `h1:` prefix and re-encodes the base64 data as hex.
I also combined the two loops over `.Deps` since I noticed `bom` doing things in this order. 🤷
=> Normalize the package hash to hex.

.github/workflows/style.yaml, pkg/commands/delete.go
The version currently used is kinda old, so this bumps it and fixes an existing warning that was annoying me locally, while developing with a newer version 😅
=> Update golangci-lint and fix issues

.github/workflows/style.yaml
We did the same in knative/.github. The `tar` errors are due to Golang packages already existing due to the `go get` or `go install` calls.
=> Run golangci-lint before tool setup to fix tar errors

pkg/build/cache.go, pkg/build/gobuild.go, pkg/build/layer.go
Start of https://github.com/google/ko/issues/264
Currently, use this by setting `KOCACHE=/tmp/ko` (or any directory you want). We can default to doing this in the future.
We will cache binaries and metdata under `$KOCACHE/bin/<import path>/<platform>`:
```
$ tree /tmp/ko
/tmp/ko                                                                                                                                                                                                                                                                                                                        
`-- bin …
```
=> Introduce KOCACHE

pkg/commands/config.go
This saves a roundtrip to the registry if we ever use the same base
image for multiple builds in a single invocation.
This also sets us up for using an on-disk cache for image metadata to
speed things up even further.
=> Cache base image metadata in-memory

.github/workflows/image.yaml
This also tags images with the commit SHA.
In my fork:
- run: https://github.com/imjasonh/ko/runs/4473935758?check_suite_focus=true
- package UI: https://github.com/imjasonh/ko/pkgs/container/ko
- image: `ghcr.io/imjasonh/ko:12ebaefe87c83c062df6a55c452d5fb247324bca`
If this goes well we can also tag images at release-time.
Not documenting in the README in this PR since I want to get more miles on it before we recommend it to people.
=> Add a workflow to push a :latest ko image to ghcr.io

pkg/build/gobuild.go, pkg/build/limit.go, pkg/build/options.go, pkg/commands/resolver.go
At least on my machine, this is slightly faster on a cold build and
saves significant time on a warm build.
Fixes https://github.com/google/ko/issues/192
=> Build each platform concurrently

.github/workflows/e2e.yaml, .ko.yaml, README.md
```
$ img=$(ko build ./)
...
$ docker run --rm \
--volume $(pwd):/src \
--workdir /src \
--volume ~/.docker:/root/.docker \
-e KO_DOCKER_REPO=quay.io/imjasonh \
${img} \
build ./ \
--sbom=none
...
quay.io/imjasonh/ko-98b8c7facdad74510a7cae0cd368eb4e@sha256:7c4c064d8ca7880b4a98674201b2c5e7c6df7fb536b5f4a470acce1a9f75f14b
```
(Pushing to quay.io since I don't have it configured to use a cred helper, which makes demonstrating this more annoying -- this also exposed https://github.com/google/ko/issues/532, which is why I'm testing with `--sbom=none`)
When we have the image pushed and tagged in the release we should add documentation for this usage in the README.
=> Add .ko.yaml to base ko container image on golang:1.17

pkg/build/gobuild.go
In the PR where we added concurrency we used a fixed length array to store
addendum to preserve the ordering from the base image when constructing the
final index.  However, with `--platform=...` this list may be filtered, which
gives us `nil` entries in our addendum.
This filters `nil` entries prior to constructing the index.
Fixes: https://github.com/google/ko/issues/544
=> Filter out nil addendum before constructing index.

.github/workflows/e2e.yaml
I believe this would have caught the concurrent build bug.
=> Add coverage of `--platform=a,b`

pkg/build/gobuild.go
Previously, we'd use the ctx from the Build invocation, but because
remote stashes the remote.WithContext option, when we later go to fetch
the actual base image to write it out to a tarball, it will fail because
the Build ctx was cancelled.
For whatever reason, NewGo takes a ctx, so this change propagates the
badness from remote so we can use the NewGo ctx when we fetch base
images.
=> Fix tarball publisher ctx handling

pkg/build/gobuild.go, pkg/commands/options/build.go
So this resolves the issue with ko hanging  on Darwin when Go is installed using ASDF, however, I'm not sure if this is the final fix that still works for everyone else.
@jonjohnsonjr 
Signed-off-by: Steve Coffman <steve@khanacademy.org>
=> Fix #530 Hanging behavior with ASDF installed Go on Darwin

.github/workflows/build.yaml, internal/sbom/mod.go, internal/sbom/mod_1.18.go
This hides our forked-from-gotip code behind a build tag so it's only
used when the build is run on Go <1.18. For builds >= 1.18, we'll use
the actual runtime/debug and debug/buildinfo packages.
Add preliminary support for building on Go 1.18beta1 to our Build
matrix, to ensure this code builds. It's all a terrible hack, but it'll
get less so when 1.18 is actually released.
(If we'd rather wait until 1.18 is actually released that's fine by me, this can wait.)
=> Prepare for Go 1.18 by replacing all our forked code

.github/workflows/e2e.yaml, pkg/commands/config.go, pkg/commands/config_test.go, pkg/commands/resolver.go
Fixes #534 
This builds on #533 to add an option to the `--platform` flag to explicitly select a platform by osversion, which happens to be necessary to select the correct `golang:1.17` base image for the GitHub Actions runner environment.
=> Support osversion when selecting base images

pkg/build/gobuild.go
This also sets layers' history creation times to the relevant times set in the tar files.
=> Set config creation time without mutating

doc/ko_apply.md, doc/ko_build.md, doc/ko_create.md, doc/ko_resolve.md, doc/ko_run.md, pkg/commands/options/publish.go, pkg/commands/resolver.go, pkg/publish/recorder.go, pkg/publish/recorder_test.go
This change adds a new `--image-refs=FILE` flag that can be used to
direct `ko` to write a file containing a `\n` delimited list of published
references.  In the common case, this will contain the list of digest
references, but if flags directing the use of tags are present this
will reflect the style of reference requested.
=> Add support for `--image-refs`

README.md
I want to use `ko` on Azure as well. I want to add how to use `ko` on Azure, as there are other examples in the README.
ref docs: Mention other deployment targets #461
Update README.
=> Add how to use Azure Container Apps

doc/ko_apply.md, doc/ko_build.md, doc/ko_create.md, doc/ko_resolve.md, doc/ko_run.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/config.go, pkg/commands/config_test.go, pkg/commands/options/build.go, pkg/commands/resolver.go
Hello! First time contributing to `ko` here 👋🏼 
- The variable `BuildOptions.Platform` was renamed to `BuildOptions.Platforms` to reflect the actual data type, though I'm not sure how comfortable are we in breaking changes of (supposedly) public structs.
- I took somewhat of a "persisting structure all the way down" approach which has a side effect of `platformMatcher.spec` and `gobuildOpener.platforms` are now of type `[]string` (instead of `string`).
Happy to discuss and make changes as desired by maintainers!
Closes #537
=> Pre-parse platform string with StringSliceVar

pkg/build/gobuild.go, pkg/build/gobuild_test.go
This change also changes behavior of GOARM, since docs suggest that it's only used when the `GOARCH=arm`, and not `arm64`.
This change should benefit users using the upcoming Go 1.18 building on base images that provide amd64 with a variant specified.
=> Set GOAMD64 if variant is set

pkg/commands/options/build.go, pkg/commands/options/build_test.go, pkg/commands/options/testdata/bad-config/.ko.yaml/.gitignore
This avoids surprises when:
- users include `.ko.yaml` in their KO_CONFIG_PATH (i.e. pointing to a file)
- users specify a wrong directory
=> Validate KO_CONFIG_PATH 

pkg/commands/config.go
Before:
```
2022/02/11 09:15:05 Using base golang:1.17 for github.com/google/ko
```
After:
```
2022/02/11 09:13:49 Using base golang:1.17 (index.docker.io/library/golang@sha256:1a35cc2c5338409227c7293add327ebe42e1ee5465049f6c57c829588e3f8a39) for github.com/google/ko
```
I couldn't tell where else to find the specific base image that was used before, without trying to guess using layer digests.
=> Log base image@digest when building

.github/workflows/sbom.yaml, go.mod, go.sum, internal/sbom/cyclonedx.go, pkg/build/gobuild.go, pkg/build/options.go, pkg/commands/deps.go, pkg/commands/resolver.go, vendor/modules.txt
Example output: https://gist.github.com/imjasonh/16185e53200bed16470e5d27e17f261e 👀 
```
cosign download sbom $(go run ./ build ./ --sbom=cyclonedx)                                                                                                                                  
```
=> Generate CycloneDX SBOMs using our own JSON generation

cmd/ko/main.go, doc/ko.md, doc/ko_apply.md, doc/ko_build.md, doc/ko_create.md, doc/ko_delete.md, doc/ko_deps.md, doc/ko_login.md, doc/ko_resolve.md, doc/ko_run.md, doc/ko_version.md, main.go, pkg/commands/root.go
This eliminates `pkg/v1/google.Keychain` log spam when gcloud is not installed and correctly configured.
This also hides `No matching credentials for ...` lines (from [here](https://github.com/google/go-containerregistry/blob/a0c4bd256482b8522065d5f6cf966281ef270680/pkg/v1/remote/transport/bearer.go#L268)) and HTTP retry logging (from [here](https://github.com/google/go-containerregistry/blob/a83d6e97daf45eebbe54d668e9a3c51d6b811d39/pkg/v1/remote/options.go#L63)).
=> Introduce --verbose flag that enables logs.Warn logs

README.md
Also tweak some wording about "publishing" images locally, since that doesn't make much sense.
=> Update 'ko publish' -> 'ko build' in README

pkg/commands/resolver.go
Hi everyone,
This PR fixes #590 and was good for me to get used with the codebase of ko.
=> feat: not enforce KO_DOCKER_REPO with push=false

pkg/build/gobuild.go, pkg/build/gobuild_test.go
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes #591 
cc: @imjasonh
=> fix: create dir for KOCACHE

pkg/commands/apply.go, pkg/commands/build.go, pkg/commands/create.go, pkg/commands/options/validate.go, pkg/commands/resolve.go, pkg/commands/run.go
warning users when using both --base-import-paths --bare flags
Partially fixes #542 
@imjasonh let me know if this is something you have in mind, otherwise, if this is not the project want we can close or improve. thanks!
```
$ ./main build --base-import-paths  --bare .
2022/02/25 17:55:08 WARNING!
-----------------------------------------------------------------
Both --base-import-paths and --bare was set.
--base-import-paths will take precedence and ignore --bare flag.
In future this will be an error
-----------------------------------------------------------------
2022/02/25 17:55:10 Using base golang:1.17@sha256:e06c83493ef6d69c95018da90f2887bf337470db074d3c648b8b648d8e3c441e for github.com/google/ko
2022/02/25 17:55:10 Building github.com/google/ko for linux/amd64
^C2022/02/25 …
```
=> warning users when using both --base-import-paths --bare flags

pkg/build/gobuild.go, pkg/build/gobuild_test.go
There were some bugs here before:
- for indexes, we'd annotate the base, but then append to empty.Index
which didn't carry those forward.
- when producing single-platform images based on multi-platform indexes
(the default and most common scenario), we wouldn't carry forward the
original base index's annotations to the single matching platform base
image.
=> Correctly pass through base image annotations

doc/ko_apply.md, doc/ko_build.md, doc/ko_create.md, doc/ko_resolve.md, doc/ko_run.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/options/build.go, pkg/commands/resolver.go
This reverts commit 7e9709a63a6bedc92020d0c4335e81a07b10e0d2
This change causes breakages when pushing to Quay.io, the fix for which (#641) causes mysterious errors in KinD.
Until we understand the compatibility story better, let's revert and unblock a v0.11 release to better support Go 1.18.
=> Revert "Produce OCI images by default (#623)"

.github/workflows/build.yaml, .github/workflows/modules-integration-test.yaml
I'm keeping Go 1.17.x as the main Go version we use in CI for now, to start slow.
=> Include builds for Go 1.18 in CI matrixes

internal/sbom/cyclonedx.go, internal/sbom/spdx.go, pkg/build/gobuild.go, pkg/commands/deps.go
This PR modifies the SPDX sbom output to include purls that add context for external tools to better infer the types of packages described in the document. 
**Note:**
As each sbom is describing the dependencies of the image it is attached to, the purl type is set to `:oci`. 
This introduces a divergence with the way the CycloneDX sbom expresses its components as the top component is a reference to golang source and not to the image. I think we should change this to express the sboms describe the images, not a go package.
/cc @imjasonh @mattmoor
=> Add purls to SPDX sbom

doc/ko_apply.md, doc/ko_build.md, doc/ko_create.md, doc/ko_deps.md, doc/ko_resolve.md, doc/ko_run.md, pkg/commands/deps.go, pkg/commands/options/build.go
Thank you for the great project. I am learning about SBOM and found that help texts and the error message seem to be incorrect.
`ko` can generate cyclonedx format, but help texts and the error message does not include cyclonedx.
I fixed help texts and the error message and ran `./hack/update-codegen.sh`.
=> Fix texts regarding SBOM

pkg/commands/options/validate.go
- add warning when using both --local and KO_DOCKER_REPO to ko.local
Address https://github.com/google/ko/issues/542#issuecomment-994194306
cc @imjasonh
=> add warning when using both --local and KO_DOCKER_REPO to ko.local

pkg/commands/options/validate.go
- check if have all and other platforms set in the --platform flag
```
../../google/ko/main build --base-import-paths \
--platform=all,linux/arm --tags v1.5.1-96-gd1a4d08-dirty --tags d1a4d086309e22cc85c0c59ac662606a58c81438 github.com/sigstore/cosign/cmd/cosign
Error: validating options: all or specific platforms should be used
2022/03/02 14:12:16 error during command execution:validating options: all or specific platforms should be used
make: *** [ko] Error 1
```
Address https://github.com/google/ko/issues/542#issuecomment-997014021
/cc @imjasonh
=> check if have all and other platforms set in the --platform flag

pkg/commands/resolver.go
This information isn't particularly sensitive, and tools sometimes run as different users, especially in a containerized environment (root vs nonroot, in Google Cloud Build, Tekton, etc).
Allow the file to be read by other users.
=> allow refs-file to be read by other users

doc/ko_build.md, pkg/commands/build.go
This changes `ko build` to not require any positional arg, and instead assume the positional arg `.` if none is passed.
This means that `ko build` can be invoked exactly, without any args, and has the same effect as `ko build .` or `ko build ./`.
This matches the behavior of `go build`.
=> build: Imply current import path

.github/workflows/e2e.yaml, pkg/commands/options/build.go, pkg/commands/options/build_test.go, pkg/commands/options/testdata/config/.ko.yaml, test/main.go
Fixes #722 
`ghcr.io/distroless/static` now includes tzdata, but this also adds a test that ensures timezone conversions are unaffected in case we change the base image again in the future.
I don't want to update the README until after we cut a release.
=> Update base image to ghcr.io/distroless/static:latest

.github/workflows/sbom.yaml, internal/sbom/spdx.go, pkg/build/gobuild.go
I mapped all of the fields from what we had to the new struct.
cc @imjasonh @jonjohnsonjr @puerco
=> Convert our SPDX SBOMs to spdx+json.

internal/sbom/cyclonedx.go
Use the simpler syntax `[2:]` to avoid the off-by-one in the length calculation.
=> Fix off-by-one error

internal/sbom/spdx.go
This PR adds the `externalDocumentRefs` field to the SPDX document. These
are required to link individual SBOMs.
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>
=> Add externalDocumentRefs to SPDX doc type

pkg/build/gobuild.go
Previously we only set this annotation when our base image was a tag, but this means when folks actually follow the best practice of use digest base images they get strictly worse resulting images!
It sounds like maybe the original motivation for this condition was that it was supposed to contain the mutable reference (tag), but I don't see anything detailing such a restriction (just an example), so there should be nothing
precluding this from the spec.
=> Unconditionally set the base image annotation.

.github/workflows/sbom.yaml, internal/sbom/cyclonedx.go, internal/sbom/mod.go, internal/sbom/mod_1.18.go, internal/sbom/spdx.go, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/commands/deps.go
Tweaking some things to prepare for the meat of: https://github.com/google/ko/issues/655
=> Start emitting multi-arch SBOMs for `SPDX` with `ko`

.ko.yaml, pkg/build/gobuild.go
Without this, if a `.ko.yaml` has:
```
builds:
- id: foo
ldflags:
- "{{ .Env.LDFLAGS }}"
```
(usually to set build-time VCS data like commit SHA, etc.)
If `LDFLAGS` isn't set, you'll get an error like:
```
Error: failed to publish images: error building "ko://blah/blah": template: argsTmpl:1:7: executing "argsTmpl" at <.Env.LDFLAGS>: map has no entry for key "LDFLAGS"
```
which is very annoying.
With this change, the build will succeed, without any additional `-ldflags` being set on the build.
=> don't fail if LDFLAGS env isn't set

internal/sbom/spdx.go
1. Change index -> image relationship type from `CONTAINS` to `VARIANT_OF` (I think this was an oversight in my original PR),
2. Always include `mediaType` in pURLs for index/images we produce (I'm not adding this to the base image, since it's not readily available, but we can add it there if we want to find a way to plumb it through),
3. Include more platform discriminator information to the pURLs we use in index -> image.
cc @puerco
=> Several SPDX SBOM adjustments.

pkg/build/gobuild.go
Currently we only decorate the topmost index/image with base image data for the base index/image (for everything except docker manifest lists).
This change makes multi-arch builds decorate the manifest of the per-architecture images with the reference of the base index, and the digest of the specific base image used for that particular architecture's image.
This results in the per-architecture SBOMs starting to encode `DESCENDENT_OF` links as well.
=> Decorate per-architecture images with base image annotations.

pkg/publish/recorder.go, pkg/publish/recorder_test.go
This change alters the behavior of `--image-refs` to also include all of the image references when a multi-architecture build is being performed.
=> Have `--image-refs` list all images for multi-arch builds.

pkg/build/gobuild.go, test/build-configs/.ko.yaml, test/build-configs/toolexec/cmd/main.go, test/build-configs/toolexec/go.mod
This came up in the discussion of https://github.com/google/ko/issues/684 -- the `-toolexec` flag makes `go build` execute another command, and generally represents pretty non-standard, advanced usage. A bad build config could set `-toolexec not-go` and get `not-go` to be executed by `go` instead of the regular Go toolchain.
`ko` aims to make normal usage easy and secure, even if it rejects advanced use cases (e.g., `CGO_ENABLED`), so we'll just reject `-trimpath` if it's requested.
=> Reject the -toolexec flag

pkg/commands/run.go
See https://github.com/google/ko/issues/747 -- `--generator` has been deprecated and remove from `kubectl`.
`kubectl run` seems to create Pods by default, so the flag wasn't necessary.
If we decide to keep `ko run` around, we should probably exercise it in some e2e test so that future similar `kubectl` changes are detected earlier.
This change also fixes an off-by-one error when handling `--`, which led to flags to kubectl being dropped. More signal that we should either use this, test it, or drop it.
Fixes #762 
Fixes #747
=> ko run: remove --generator flag

.ko.yaml
I'd like to use ghcr.io/google/ko in a tekton pipeline to build karpenter which uses go 1.18.
Before
```
2022/07/13 23:53:57 logged in via /root/.docker/config.json
2022/07/13 23:54:46 Using base [ghcr.io/distroless/static:latest@sha256:9a2c27a6be0723f18630c26f601fc83a2bee1af0706906a694df3fda05a32267](http://ghcr.io/distroless/static:latest@sha256:9a2c27a6be0723f18630c26f601fc83a2bee1af0706906a694df3fda05a32267) for cmd/controller/main.go
2022/07/13 23:54:47 Building cmd/controller/main.go for linux/amd64
2022/07/14 00:01:33 Unexpected error running "go build": exit status 2
/go/pkg/mod/golang.org/x/exp@v0.0.0-20220303212507-bbda1eaf7a17/constraints/constraints.go:13:2: syntax error: unexpected ~, expecting method or interface name …
```
=> Chore: bumped base image to go 1.18

.github/workflows/go-1.18.yaml
I messed this up in #772 -- the test needs `env:` instead of `with:` (which requires a `uses:`)
=> fix GitHub Actions workflows

pkg/build/gobuild.go, pkg/build/gobuild_test.go
We currently always append layers with Docker media types, even if the base image is an OCI image (e.g., our new default base image, `ghcr.io/distroless/static`)
This works fine against some registries (GCR), but not against others (apparently Quay, Gitlab Registry, probably others).
This was reported in https://github.com/tektoncd/pipeline/issues/5188 since Tekton switched its base image for git-init to ghcr.io/distroless/git
This changes our layer creation to check for the type of the base image, and set layer media types accordingly.
=> Set layer media types consistently

.github/workflows/kind-e2e.yaml, pkg/publish/kind/write.go
Also include more logs when kind load fails.
=> Add kind e2e test for ko run

.github/workflows/quay.yaml, .github/workflows/registries.yaml
These rely on long-lived credentials stored in GitHub repository secrets.
We should also investigate adding tests for ECR and GCR using OIDC credentials, probably reusing those used by go-containerregistry.
=> Add tests that ko can push to quay.io and Dockerhub

.github/workflows/registries.yaml
And Quay.io still doesn't accept our SBOMs.
=> Fix e2e push tests, these registries need --bare

pkg/commands/apply.go, pkg/commands/create.go, pkg/commands/resolve.go, pkg/commands/resolver.go
this exposes `commands.ResolveFilesToWriter()` to allow downstream consumers to more easily leverage `ko resolve` like functionality through available apis instead of reimplementing it.
=> expose commands.ResolveFilesToWriter() method

README.md
Adds message about the upcoming move of the ko project to its own org: [ko-build](https://github.com/ko-build), to facilitate the needs of growing community.
=> adds org move message

pkg/commands/options/build.go
At this time, `distroless.dev/static` simply redirects to `ghcr.io/distroless/static`, so this is effectively no change since #722.
However, we are evaluating renaming the github.com/distroless org to avoid confusion, and in doing so, images at ghcr.io/distroless may be disrupted. Using the distroless.dev redirector gives us flexibility to change the underlying image registry transparently.
The redirector code for distroless.dev is open source at https://github.com/chainguard-dev/registry-redirect and we've used it extensively internally for a month or two with no serious issues.
Any credentials that are used are not logged or stored by the redirector, and since the image in question is public anyway, any credentials that pass through the redirector have no elevated permissions.
=> update default base image to distroless.dev/static

pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/gobuilds_test.go, pkg/commands/publisher_test.go, pkg/commands/resolver_test.go
Fixes #699
If the user specifies an image manifest and its platform does not match the platforms specified or defaulted, error out.
With a `.ko.yaml` specifying the linux/amd64 image manifest instead of the multi-platform index:
```yaml
baseImageOverrides:
github.com/google/ko: golang@sha256:a4081692fa3015104d84b125cbf623c566a0c9e2a39b9a29f6d939225d5687a4
```
```
❯ go run main.go build --platform=linux/arm64 .
2022/08/04 10:36:41 No matching credentials were found, falling back on anonymous
2022/08/04 10:36:42 Using base golang@sha256:a4081692fa3015104d84b125cbf623c566a0c9e2a39b9a29f6d939225d5687a4 for github.com/google/ko
2022/08/04 10:36:42 Building github.com/google/ko for linux/amd64
...
```
```
❯ go run main.go build --platform=linux/arm64 .
2022/08/04 10:43:52 No matching …
```
=> Error if image platform does not match desired

pkg/commands/resolver.go
Prior to this, if I set `KO_DOCKER_REPO=kind.local/foo/bar`, this logic would attempt to publish to a remote registry named `kind.local`. Same with `ko.local`.
=> Extend ko.local and kind.local detection to include sub-repos

.github/workflows/e2e.yaml, pkg/commands/resolver.go
Supercedes #689
cc @adambkaplan
With this change, if you use `--push=false` and `-t`, the output ref includes the tag. If you include `--tag-only` the resulting output ref will only include the tag, and _not_ the digest. I'm not sure what purpose that would be useful for, but it's consistent with pushing cases at least.
=> Support --tag and --tag-only with nop publisher

.github/workflows/sbom.yaml, internal/sbom/spdx.go
This commit fixes the package manager label in external references
to make them [conform to the SPDX spec](https://spdx.github.io/spdx-spec/package-information/#721-external-reference-field).
/cc @imjasonh 
Signed-off-by: Adolfo Garcia Veytia (puerco) <puerco@chainguard.dev>
=> SPDX: Fix package manager label

internal/sbom/spdx.go
This PR modifies the ko SPDX SBOMs to generate documents conformant to version 2.3 of the spec. It makes use of the new
primary package purpose field to add a hint marking the packages as container images.
Follow-up to: https://github.com/google/ko/pull/801
/cc @imjasonh 
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>
=> SPDX 2.3 support

.github/workflows/e2e.yaml, README.md, doc/ko_apply.md, doc/ko_build.md, doc/ko_create.md, doc/ko_resolve.md, doc/ko_run.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/options/build.go, pkg/commands/resolver.go
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes #728
=> feat: write sbom result to disk

README.md, pkg/publish/default.go, pkg/publish/options.go
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes #819
=> feat: adding support for using multiple keychain for sending sbom results to a different repository

go.mod, go.sum, vendor/go.mongodb.org/mongo-driver/bson/bsonoptions/doc.go, vendor/modules.txt
Fixes https://github.com/ko-build/ko/issues/832
```
go get -u go.mongodb.org/mongo-driver@latest
go mod vendor
```
cc @bentheelder
=> bump mongo dep to avoid retracted version

README.md
Signed-off-by: jwcesign <jwcesign@gmail.com>
Fix #https://github.com/ko-build/ko/issues/838
Add some description how to pass `kubectl apply` parameters
=> Add -- usage in readme

docs/get-started.md
Fixes the 404 error when clicking the link to the _Installation_ page located at the top of the _Getting Started_ page.
=> doc: fix link to Installation page in Getting Started

pkg/commands/resolver.go
Before this change, the file at `--image-refs` would be opened, and written to from the beginning. If there were any existing contents in that file already, they would be potentially partially overwritten.
With this change, we open and truncate the file, so that any writes start from the beginning of a fresh new file.
This was reported via https://github.com/knative/serving/pull/13408/
=> truncate -image-refs file

pkg/commands/resolver.go, pkg/commands/resolver_test.go
Fixes https://github.com/ko-build/ko/issues/807
cc @developer-guy 
See comments in https://github.com/ko-build/ko/issues/807#issuecomment-1243695345 -- uniformly setting `base: po.LocalDomain` in `NewDaemon` was fine when we assumed/required that `KO_DOCKER_REPO=ko.local` would only be used without a repo, but we've since changed that assumption/requirement.
```
$ KO_DOCKER_REPO=ko.local/foo go run ./ build ./test --bare
...
ko.local/foo:3a28632fcb886b7a4c78be8cd36c34ec47e83f71ff55353e5602873400dca564
```
Note that this also handles `ko.local/foo` for other namers:
```
$ KO_DOCKER_REPO=ko.local/foo go run ./ build ./test --preserve-import-paths
...
ko.local/foo/github.com/google/ko/test:3a28632fcb886b7a4c78be8cd36c34ec47e83f71ff55353e5602873400dca564
```
```
KO_DOCKER_REPO=ko.local/foo go …
```
=> Handle KO_DOCKER_REPO=ko.local/repo and --bare correctly

mkdocs.yml
This uses https://github.com/mkdocs/mkdocs-redirects to redirect some ko.build paths to external URLs.
For example, https://ko.build/prs will redirect to https://github.com/ko-build/ko/pulls
I tried to figure out how to get ko.build/i/NNN to redirect to a specific issue, but I couldn't get anything to work.
Let me know if there's anything else you think we should add.
=> ko.build: support some common shortlinks

docs/install.md
```
-S, --show-error
When used with -s, --silent, it makes curl show an error message if it fails.
-f, --fail
(HTTP) Fail silently (no output at all) on server errors. This is mostly done to enable scripts etc to better deal with failed attempts. In
normal cases when an HTTP server fails to deliver a document, it returns an HTML document stating so (which often also describes why and
more). This flag will prevent curl from outputting that and return error 22.
```
=> install: fail with 404 instead of gzip error when url was wrong

pkg/commands/resolver.go
Signed-off-by: Nico Braun <rainbowstack@gmail.com>
resolve: #883
=> feat: deduplicate tags

.github/workflows/publish-site.yaml
https://github.com/ko-build/ko/pull/872 added redirects, but didn't install the mkdocs redirect plugin when publishing.
=> install mkdocs-redirect when publishing site

pkg/publish/default.go, pkg/publish/tarball.go
Noticed this while reviewing https://github.com/ko-build/ko/pull/884 -- it's weird that `defaultTags` is always a slice (and necessarily a `var`) when we only care about its only element, which is `"latest"`.
=> nit: replace one-item slice with const

.github/workflows/release.yml
Sigstore made a breaking change as part of their recent GA announcement. We need a temporary fix to avoid builder failure (see slsa-framework/slsa-github-generator#1163)
/cc @asraa @ianlewis
=> Temp fix for SLSA generators

.github/workflows/release.yml
Rekor had a braking change as part of their GA announcement. This PR updates the verifier to v1.3.2
=> Fix verifier

pkg/build/gobuild.go
while working on https://github.com/goreleaser/goreleaser/pull/3653, I got some race conditions sometimes.
Seems to happen when the base image is a image index, in which case it'll build for all platform needed concurrently, which is when we get the concurrent writes.
I don't see a big issue in returning a copy instead, not sure what you think.
PS: Its late here, so please pardon me if I'm doing something dumb 😂
=> fix: possible race condition when applying templates to flags/ldflags

docs/configuration.md, pkg/commands/options/build.go
distroless.dev/static redirects to exactly the same location as cgr.dev/chainguard/static (and will indefinitely). cgr.dev has the added benefit that it has probers and oncall.
The docs change is more important; that was just plain incorrect since [`v0.12.0`](https://github.com/ko-build/ko/releases/tag/v0.12.0).
=> update docs to reflect actual default base image

main.go
Cobra logs error messages before passing them to us, so we don't need to re-log it.
Before:
```
ko build ./blah
Error: failed to publish images: importpath "ko://./blah" is not supported: importpath is not `package main`
2023/01/04 11:30:41 error during command execution:failed to publish images: importpath "ko://./blah" is not supported: importpath is not `package main`
exit status 1
```
After:
```
go run . build ./blah
Error: failed to publish images: importpath "ko://./blah" is not supported: importpath is not `package main`
exit status 1
```
=> remove repeated error message on failure

pkg/commands/options/build.go
=> fix KO_CONFIG_PATH pointing to a file

mkdocs.yml
This will make https://ko.build/slack link to the `#ko-build` Slack channel on the Kubernetes Slack.
=> add ko.build/slack short link

pkg/build/gobuild.go, pkg/build/gobuild_test.go
Docker decided to include provenance attestations in index manifests, with descriptors having the platform `unknown/unknown`: https://docs.docker.com/build/attestations/attestation-storage/#image-index-sha25694acc2ca70c40f3f6291681f37ce9c767e3d251ce01c7e4e9b98ccf148c26260
This causes problems for `ko build --platform=all` since `unknown/unknown` is not a, well, known GOOS/GOARCH, in accordance with the [OCI image spec](https://github.com/opencontainers/image-spec/blob/main/image-index.md#image-index-property-descriptions).
This change ignores `unknown/unknown` when trying to match a multi-arch base image's platforms, even when using `--platform=all`.
=> fix: handle docker's unknown/unknown platform in index manifests

pkg/build/gobuild.go
=> fix file extension for cyclonedx

.github/workflows/release.yml
Fixes #978 
Uses the `attestation-name` output from `generator_generic_slsa3.yml` to get the artifact name to download.
Also removes the `compile-generator` input as https://github.com/slsa-framework/slsa-github-generator/issues/1163 was fixed.
=> fix: Use attestation-name output

.github/workflows/release.yml, .goreleaser.yml, hack/boilerplate/boilerplate.sh.txt
- add tag name to the provenance
- refactor release job
- update deprecated Goreleaser flags
- and other cosmetic updates
Rehearsal here: https://github.com/cpanato/ko/actions/runs/4416634779 / https://github.com/cpanato/ko/releases/tag/v99.99.02
Image:
```
$ cosign verify --certificate-oidc-issuer "https://token.actions.githubusercontent.com" --certificate-identity "https://github.com/cpanato/ko/.github/workflows/release.yml@refs/tags/v99.99.02" ghcr.io/cpanato/ko:v99.99.02 | jq .
Verification for ghcr.io/cpanato/ko:v99.99.02 --
The following checks were performed on each of these signatures:
- The cosign claims were validated
- Existence of the claims in the transparency log was verified offline
- The code-signing certificate was verified using trusted certificate authority certificates …
```
=> refactor release job 

.github/workflows/analyze.yaml
Recently the `Analyze` workflow has started to fail mysteriously (see https://github.com/ko-build/ko/pull/991)
The commit we pin two is [only a few weeks old](https://github.com/github/codeql-action/commit/a589d4087ea22a0a48fc153d1b461886e262e0f2/) but there have been [some changes](https://github.com/github/codeql-action/compare/a589d4087ea22a0a48fc153d1b461886e262e0f2...168b99b3c22180941ae7dbdd5f5c9678ede476ba) particularly https://github.com/github/codeql-action/commit/100bd7bbef94953be41fddd5afa784161cf2b4c5 which seems like it might be the fix.
I'm not sure why `168b999` was picked up, as it's not (currently) `v2.2.7` -- maybe they retagged to pick up the fix, I'm not sure.
=> try to fix codeql workflow

pkg/commands/resolver.go
https://github.com/ko-build/ko/pull/820 might have been a regression?
=> Fix --local with KO_DOCKER_REPO

.github/workflows/e2e.yaml, pkg/build/gobuild.go
:bug: Right now `--sbom-dir` with a multi-arch build just writes the same file over and over.
This loosely follows the lead of apko which uses the form `sbom-{arch}.{form}.json`, but we are going with: `{app}-{platform}.{form}.json`.
It is notable that `{platform}` is a superset of `{arch}` and we sanitize the string encoding replacing the `/` and `:` characters with `-`.
/kind bug
=> Fix: Incorporate platform architecture

pkg/publish/kind/write.go
Reverts ko-build/ko#1026
This failed unit tests: https://github.com/ko-build/ko/actions/runs/5058723077/jobs/9079218316
```
--- FAIL: TestWrite (0.02s)
write_test.go:62: c.cmd = ctr --namespace=k8s.io images import --all-platforms -, want ctr --namespace=k8s.io images import -
```
=> Revert "Fix kind image loading for MacOS"

pkg/commands/cache.go, pkg/commands/config.go
This speeds up repeated builds by caching manifests and config files locally under `${KOCACHE}/img`.
Before:
```
ko build .  1.09s user 2.37s system 148% cpu 2.326 total
```
After:
```
ko build .  1.05s user 2.29s system 244% cpu 1.366 total
```
(Most of the time difference comes from not having to do the TLS handshake with DockerHub to fetch the golang stuff.)
This has a nice effect of allowing offline builds with `ko` if your base images are referenced by digest _and_ you pre-pull the images into `${KOCACHE}/img`.
This does not cache base image layers by default because they are often present in the destination registry and would slow things down and take up space.
It might make sense to add a command or flag to completely cache the base image, but we could also just add some docs about …
=> implement dumb cache for images

pkg/commands/cache.go
This picks up two dropped `err` variables in `pkg/commands`.
=> pkg/commands: fix dropped errors

.github/workflows/build.yaml
https://github.com/golang/govulncheck-action
```
govulncheck ./...        
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.
Using go1.20.7
and govulncheck@v0.2.0 with vulnerability data from https://vuln.go.dev (last modified 2023-08-02 20:33:39 +0000 UTC).
Scanning your code and 658 packages across 111 dependent modules for known vulnerabilities...
```
(no vulns 😎)
=> ci: add govulncheck

docs/install.md
Hello, I recently created a pr in the main bucket of [Scoop](https://github.com/ScoopInstaller/Main/pull/5035), to add Ko as a package. This allows Windows users to install Ko using the `scoop install ko` command on Windows and makes using this great tool a lot easier. :-).
As soon as the pr in the Scoop repo is merged, I'd like to update the docs how to install Ko on Windows.
=> Update install docs to install ko using Scoop

pkg/build/gobuild.go
This doesn't change much for users of `ko` as a CLI, the output still contains relevant error output:
```
$ go run ./ build ./test/                                 
2023/09/07 09:18:11 Using base cgr.dev/chainguard/static:latest@sha256:a432665213f109d5e48111316030eecc5191654cf02a5b66ac6c5d6b310a5511 for github.com/google/ko/test
2023/09/07 09:18:11 Building github.com/google/ko/test for linux/amd64
Error: failed to publish images: error building "ko://github.com/google/ko/test": build: go build: exit status 1: # github.com/google/ko/test
test/main.go:80:1: syntax error: non-declaration statement outside function body
```
Previously, this was:
```
ko build ./test/
2023/09/07 09:19:21 Using base cgr.dev/chainguard/static:latest@sha256:a432665213f109d5e48111316030eecc5191654cf02a5b66ac6c5d6b3 …
```
=> include go build output in build error

.github/dependabot.yml, .github/workflows/build.yaml, .github/workflows/e2e.yaml, .github/workflows/image.yaml, .github/workflows/kind-e2e.yaml, .github/workflows/modules-integration-test.yaml, .github/workflows/publish-site.yaml, .github/workflows/registries.yaml, .github/workflows/release.yml, .github/workflows/sbom.yaml, .github/workflows/style.yaml, .github/workflows/test.yaml, .github/workflows/verify.yaml, .ko.yaml, go.mod
- remove pull_request-target and make registry job only postsubmit
- update config for dependabot
- drop go1.19, use go1.21 as default for ci and release
- add golangci-lint job
- use go1.21 as base image
- update go module to require minimum go1.20
=> Use go1.21, clean up ci and drop go1.19

.golangci.yaml, internal/sbom/cyclonedx.go, pkg/build/cache.go, pkg/build/gobuild.go, pkg/build/limit_test.go, pkg/commands/apply.go, pkg/commands/create.go, pkg/publish/kind/write_test.go, pkg/publish/options.go, pkg/publish/shared_test.go
depguard is disabled because its new default config is to only allow stdlib deps (i.e., make you explicitly list each dep in your linter, for some reason) https://github.com/golangci/golangci-lint/issues/3877
deadcode is disabled because it's unmaintained and warns when you use it.
The rest of the changes fix findings reported by newer versions of golangci-lint
=> handle newfound lint errors

pkg/build/gobuild.go
https://github.com/ko-build/ko/pull/1142 broke a test for Windows platform matching.
=> fix test broken by lint fix

.github/workflows/e2e.yaml
fix env var for go env
follow up of https://github.com/ko-build/ko/pull/1141
=> fix env var for go env

pkg/commands/cache.go
I have a suspicion that this is causing a race where we modify the cache's index.json file before we actually write out the image's config file, so if we call RawConfigFile before we finish caching it, we'll just fail to find that file.
=> Don't AppendDescriptor until we've written config

docs/community.md
Community page stated biweekly meeting was at `Wednesdays at 1:00 AM US Eastern time, 10:00 AM US Western time`. The 'AM' for US Eastern is likely intended to be a 'PM'.
=> Fix "AM" Time Typo

docs/install.md
Add details on how to install `ko` on macOS using MacPorts: https://ports.macports.org/port/ko/
=> docs: add MacPorts install info

mkdocs.yml
I noticed that the code blocks lack styling, which makes them just a little bit harder to read.
This PR updates the `mkdocs.yaml` file to add in the required styling as per [the documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/)
As far as I know, there should not be any additional imports required for the mkdocs GHA
---
_note: I have got a previous CLA with Google_
=> (feat) Adding styling to code blocks

pkg/publish/kind/write.go
This fixes the error message when no nodes exist to print the correct cluster name.
=> Correct cluster name in error message when no nodes are found

docs/deployment.md
Fixes https://github.com/ko-build/ko/issues/1186
=> Fix fly.io deployment docs

pkg/commands/resolver.go, pkg/publish/kind.go
Make the functionality match between:
KO_DOCKER_REPO=ko.local/my-image ko build --bare
And:
KO_DOCKER_REPO=kind.local/my-image ko build --bare
As it stands, `--bare` is broken with `kind.local/` as it just gets `kind.local` as the image name, and then it fails to tag because the registry is missing.
=> Fix kind image names with --bare

go.mod, integration_test.sh, pkg/build/config.go, pkg/build/gobuild.go, pkg/caps/caps.go, pkg/caps/caps_dd_test.go, pkg/caps/caps_test.go, pkg/caps/gen.sh, pkg/caps/new_file_caps_test.go, pkg/commands/options/build.go, test/build-configs/.ko.yaml, test/build-configs/caps.ko.yaml, test/build-configs/caps/cmd/main.go, test/build-configs/caps/go.mod
This patchset adds `linux_capabilities` under `builds` [section](https://ko.build/configuration/#overriding-go-build-settings) in `.ko.yaml`. Ex:
```yaml
builds:
- id: my-app
dir: ./cmd
main: ./myapp
linux_capabilities: bpf perfmon net_admin
```
A bit of trivia on capabilities: unless running the app as root user, Docker's `--cap-add` alone is insufficient.
Requested capabilities are AND-combined with capabilities granted to the app binary (intentionally simplified, see `man capabilities` for the full discourse).
A running program has multiple sets of capabilities. The most important ones are `effective` (used by the kernel for permission checks) and `permitted` (a "stash" of capabilities an app can promote to effective). Likewise, file capabilities capture multiple sets of capabilities, …
=> Add support for setting capabilities on the app binary

docs/configuration.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/options/build.go, pkg/commands/options/build_test.go, pkg/commands/options/testdata/config/.ko.yaml, pkg/commands/resolver.go
Supports configuring global `env` variables that will be applied to all builds.
Modifies the `builder` function to accept a `buildContext` structure. This will simplify similar modifications in the future.
Fixes #1305
=> feat: Add global env

docs/configuration.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/internal/git/errors.go, pkg/internal/git/git.go, pkg/internal/git/info.go, pkg/internal/git/info_test.go, pkg/internal/gittesting/git.go, pkg/internal/gittesting/git_test.go
This includes a number of template parameters supported by [goreleaser](https://goreleaser.com/customization/templates/). Specifically, the build date information and the majority of the Git params.
Majority of the code is copied from goreleaser. I've added the MIT license from goreleaser at the top of the files.
Fixes #493
=> feat: Add template params for git

docs/configuration.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/options/build.go, pkg/commands/options/build_test.go, pkg/commands/options/testdata/config/.ko.yaml, pkg/commands/resolver.go
=> Add global flags and ldflags

docs/configuration.md, integration_test.sh, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/options/build.go, pkg/commands/options/build_test.go, pkg/commands/options/testdata/config/.ko.yaml, pkg/commands/resolver.go
There was recent work to add global values for `env`, `flags`, and `ldflags`. The global values would be merged with per-build values to generate the value used for the builds.
There are a couple issues with this:
- It's inconsistent with the existing code, which only has `default` values declared globally (there is no merging today).
- The name of the `flag` variable, caused a conflict with knative's `KO_FLAGS` environment variable (see https://github.com/ko-build/ko/issues/1317)
This PR does the following:
- Refactors the logic to use `defaultEnv`, `defaultFlags`, and `defaultLdflags`. This resolves both issues described above.
- Updates documentation
Fixes https://github.com/ko-build/ko/issues/1317
=> Refactor global values to be defaults

docs/advanced/terraform.md
The field name of `image` does not exist per https://registry.terraform.io/providers/ko-build/ko/latest/docs/resources/build#read-only.
Found this problem while trying to use it, and confirmed it working with this fix.
=> Fix a typo in terraform.md

.github/workflows/e2e.yaml, docs/features/debugging.md, docs/reference/ko_apply.md, docs/reference/ko_build.md, docs/reference/ko_create.md, docs/reference/ko_resolve.md, docs/reference/ko_run.md, mkdocs.yml, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/options/build.go, pkg/commands/resolver.go, pkg/internal/git/clone.go
Picking up the awesome work from https://github.com/ko-build/ko/pull/1148, just resolving current conflicts and seeing if we can get this merged.
I've tested this running the built container in Docker Desktop on macOS, using GoLand (running natively on macOS), and it appears to work great.
If there's anything further this PR needs, I'm happy to help out. I'd love to see this `--debug` flag in `ko`! 😃 
cc: @imjasonh
=> Add debug flag to include delve

.github/workflows/e2e.yaml, .github/workflows/kind-e2e.yaml
also skipping the one tests for windows when we add the debug options, seems to not work, need some research, but commenting out to unblock other PRs
=> update k8s for kind e2e tests

pkg/build/gobuild.go, pkg/build/gobuild_test.go
Adds the `--` separator parameter so delve doesn't try to parse any command line parameters intended for the target binary.
=> debug: separate target and delve parameters

docs/advanced/faq.md
=> Fix config links

docs/reference/ko_apply.md, docs/reference/ko_build.md, docs/reference/ko_create.md, docs/reference/ko_resolve.md, docs/reference/ko_run.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/options/build.go, pkg/commands/resolver.go
This adds a new build flag for setting annotations on image indexes and manifests.
Annotations are no longer copied from the base image. `org.opencontainers.image.base.digest` and
`org.opencontainers.image.base.name`
are always set to the resolved values.
Usage example:
```sh
ko build --image-annotation foo=bar,fizz=buzz .
```
Fixes #1090
Fixes #1090
Fixes #1231
Fixes #1235
Fixes #1395
=> allow setting annotations

pkg/commands/resolver.go, pkg/publish/recorder.go, pkg/publish/recorder_test.go
Currently the resolver command creates the image-refs file on initialization. This causes git to be dirty during builds. This change moves the file creation to be in the recorder itself and on the first time the Publish() method is called. This happens after the build so git is clean. This will mean that any errors on file creation will be reported after the build rather than before.
Fixes #1378
=> Update recorder to lazy create file.

pkg/commands/resolver.go, pkg/publish/layout.go, pkg/publish/layout_test.go, pkg/publish/multi_test.go
When using ko with OCI Layout, Git status will always be dirty because the layout is created before this build. This changes the layout to be created after the build so that git will be clean. The means that any error creating the layout won't be seen until after the build.
=> Change OCI Layout publisher to lazy create layout after build.

.github/workflows/style.yaml, .gitignore, .wokeignore, hack/presubmit.sh, hack/update-codegen.sh, hack/update-deps.sh
The vendor directory was removed in 38a1feb0, but it lives on in some places (largely development/contribution and linting).  This change removes those remaining references.
=> Remove remaining references to `vendor/`

docs/reference/ko_apply.md, docs/reference/ko_build.md, docs/reference/ko_create.md, docs/reference/ko_resolve.md, docs/reference/ko_run.md, pkg/build/gobuild.go, pkg/build/gobuild_test.go, pkg/build/options.go, pkg/commands/options/build.go, pkg/commands/resolver.go
Hello! :wave:
When using a base image that does not set a user (e.g. `busybox`), it is desirable to set a non-root user for the built image. At the moment, this requires building a custom image built with another tool to set this value. Since it is a simple config field, it seems reasonable to have an option for it
=> feat: add image user option

.github/workflows/release.yml
We can't use the latest release to build the latest release.
=> Remove cycle in release process

docs/advanced/migrating-from-dockerfile.md
The Dockerfile example, whilst not functional at all, is not readable with the current formatting applies
This PR updates the formatting on the mkdocs site
=> fix(formatting): Updated the codeblock for Dockerfile to make it more readable

pkg/build/gobuild.go
When use `--debug` build flag, a new dlv executable file is built into the image. However, during the build, some build flags are not specified, resulting in the binary being different each time, which ultimately causes the digest of the image to be inconsistent.
This change aims to ensure that, as long as the remote dlv code has not been updated, the digest remains consistent with each build.
=> fix(debug): ensure reproducible builds in debug mode

docs/features/k8s.md
When trying out these examples, it is easier to have a deployment that can be copied and quickly tested. I don't think it adds too much clutter and it definitely saves people to troubleshoot why what they copied from the site doesn't work.
=> Adding labels to make it easier k8s.md

pkg/build/gobuild.go, pkg/build/gobuilds_test.go
This reverts commit 3f2f5a5d2c4482a80ba2a11af9f9021d0190f247.
Since `ko v0.18.0`, mostly empty SBOMs have been generated. While investigating the cause of this, I noticed that the `-m` flag was removed from `go version -m` by commit 3f2f5a5d2c4482a80ba2a11af9f9021d0190f247. If the `-m` flag is not specified, module versions are not outputted, resulting in the generation of SBOMs that do not include module information.
> $ go help version
> usage: go version [-m] [-v] [file ...]
> [...]
> The -m flag causes go version to print each file's embedded
> module version information, when available. In the output, the module
> information consists of multiple lines following the version line, each
> indented by a leading tab character.
This PR resolves this issue by reverting the commit that …
=> Revert "drop -m flag" to fix empty SBOM generation in `v0.18.0`

.github/workflows/release.yml
We noticed that using the ko docker image it is currently not possible to build projects that specify the latest go version in their `go.mod`:
```
docker run -v .:/tmp/demo -w /tmp/demo ghcr.io/ko-build/ko:v0.17.1 build . --push=false 
Error: failed to publish images: qualifying local import : err: exit status 1: stderr: go: go.mod requires go >= 1.24.0 (running go 1.23.2; GOTOOLCHAIN=local)
```
I guess all that would be needed is to just create a new release, that rebuilds the images, since the ko image always uses the [latest golang image as its base](https://github.com/maboehm/ko/blob/f7d9dd7717cb3b1ba46576ade1f85f233ccb1a73/.ko.yaml#L2).
To prepare that it probably makes sense to run the tests against these versions, and then a new release could be published.
=> Update ko version used in CI
