- pkg/build/gobuild.go
This avoids double-compressing later.
On my CPU-constrained laptop, this shaves ~30% of the time off of `ko publish` in cases where we actually have to upload the blob.
On my pretty beefy desktop it's closer to ~15%.
> Compress layers when we Build them

- README.md
[Under the covers](https://idioms.thefreedictionary.com/under+the+covers) has an unintended connotation here and is a less appropriate idiom than [under the hood](https://encyclopedia2.thefreedictionary.com/under+the+hood).
> Use a more appropriate idiom in README

- pkg/resolve/selector.go
- pkg/resolve/selector_test.go
Fixes https://github.com/google/ko/issues/62
cc @ZhiminXiang
> Fix multi-doc yaml re-joining

- README.md
Fixes https://github.com/google/ko/issues/85
> Update README to include better install instructions

- pkg/publish/options.go
> Rework parsing logic

- .ko.yaml
- README.md
- cmd/ko/test/test.yaml
- pkg/build/gobuild.go
- pkg/commands/config.go
- pkg/commands/publisher.go
Related: https://github.com/google/ko/issues/158
Related: https://github.com/google/ko/issues/160
> This adds the deprecation notices for ko:// and nonroot

- .travis.yml
A bit of an orthogonal cleanup in preparation of #180
> Update kind to the latest release.

- pkg/resolve/selector_test.go
Found by: https://github.com/google/ko/pull/194
> Fix goimports

- .github/workflows/knative-boilerplate.yaml
- .github/workflows/knative-donotsubmit.yaml
- .github/workflows/knative-go-build.yaml
- .github/workflows/knative-go-test.yaml
- .github/workflows/knative-stale.yaml
- .github/workflows/knative-style.yaml
- .github/workflows/knative-verify.yaml
- pkg/build/gobuild_test.go
Produced via:
```shell
cp $(find "${GITHUB_WORKSPACE}/meta/workflow-templates" -type f -name '*.yaml') \
"${GITHUB_WORKSPACE}/main/.github/workflows/"
```
/cc @jonjohnsonjr @ImJasonH
/assign @jonjohnsonjr @ImJasonH
> [Automated] Update actions

- pkg/build/gobuild.go
Fixes: https://github.com/google/ko/issues/199
> Print more complete platform information.

- README.md
Produced via:
```shell
prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github | grep -v docs/cmd/)
```
/cc @jonjohnsonjr @ImJasonH
/assign @jonjohnsonjr @ImJasonH
> [Automated] Format markdown

- README.md
This is just #122 with 100% more CLA signing
@mauilion
> Fix API Versions in README.md

- README.md
There were no links to kind in the README prior to this PR
> Update README with link to kind

- README.md
Fixes #219
As per title. Not much more to say.
> Document usage of KIND_CLUSTER_NAME

- .github/workflows/kind-e2e.yaml
- .travis.yml
- cmd/ko/test/main.go
- pkg/publish/daemon.go
Fixes: https://github.com/google/ko/issues/224
> Run the hello test on multiple architectures

- pkg/commands/options/publish.go
- pkg/publish/default.go
Fixes https://github.com/google/ko/issues/246
> Stop using filepath.Join in publisher

- pkg/commands/resolver.go
Fixes https://github.com/google/ko/issues/249
The dep-notify package doesn't know anything about ko, so we need to
trim the strict prefix before sending import paths over to it.
> Make --watch work with ko://

- .goreleaser.yml
> [RELEASE 0.7] Fix .goreleaser.yml

- README.md
In #289 I messed up the link to releases. This points to correct location.
> Fix the link to releases

- .github/workflows/stale.yaml
> Fix typo in stale GitHub Action

- .github/workflows/kind-e2e.yaml
Also:
- collect and upload logs as build artifacts
- don't bother testing many k8s versions
- don't checkout and install into GOPATH
- install ko from ./ to avoid warning
- remove unnecessary knative cruft
> Use helm/kind-action to set up KinD cluster

- .github/workflows/modules-integration-test.yaml
- hack/boilerplate/boilerplate.go.txt
- pkg/commands/commands.go
- pkg/commands/deps.go
Fixes https://github.com/google/ko/issues/402
> Implement ko deps

- pkg/build/gobuild.go
Fixes https://github.com/google/ko/issues/432
> Drop scary warning

- pkg/build/gobuild.go
- pkg/build/gobuild_test.go
> Fix regression in adding /ko-app to PATH

- pkg/commands/create.go
> Don't log the value of --password if given

- pkg/commands/deps.go
> Clean filepath from zip before creating tempdir

- README.md
> Document /ko-app/ and entrypoint in README.md

- pkg/build/cache.go
Fixes https://github.com/google/ko/issues/579
> Add a mutex to map writing when using KOCACHE

- .github/workflows/image.yaml
Annotate signature with run information
edit: example successful run: https://github.com/imjasonh/ko/runs/5174710473?check_suite_focus=true
> Sign image using cosign

- .github/dependabot.yml
- .github/workflows/boilerplate.yaml
- .github/workflows/donotsubmit.yaml
- .github/workflows/kind-e2e.yaml
- .github/workflows/style.yaml
Also adds dependabot config to bump the action definitions via PRs.
> Take advantage of Chainguard maintained versions of various actions.

- pkg/build/gobuild.go
See https://github.com/chainguard-dev/apko/issues/22
> Clear Cmd when setting Entrypoint

- .github/workflows/build.yaml
- .github/workflows/e2e.yaml
- .github/workflows/go-1.18.yaml
- .github/workflows/image.yaml
- .github/workflows/kind-e2e.yaml
- .github/workflows/modules-integration-test.yaml
- .github/workflows/release.yml
- .github/workflows/sbom.yaml
- .github/workflows/stale.yaml
- .github/workflows/style.yaml
- .github/workflows/test.yaml
- .github/workflows/verify.yaml
- check and use the latest go available for the defined version 
- update cosign action and version
cc @imjasonh
> check and use the latest go available for the defined version 

- pkg/commands/options/build.go
- pkg/commands/options/build_test.go
- pkg/commands/options/testdata/config/my-ko.yaml
> Allow KO_CONFIG_PATH to be a file

- internal/sbom/spdx.go
WIP until https://github.com/google/ko/pull/743 lands.
I'm going to split off the annotation change as well, but including here so that things work.
> Add base image information to SPDX SBOMs

- README.md
> Add installation instructions for Alpine

- README.md
Signed-off-by: Ian Lewis <ianlewis@google.com>
> Update setup-ko version

- CONTRIBUTING.md
- ROADMAP.md
- code-of-conduct.md
> add CONTRIBUTING, code of conduct, roadmap

- README.md
- docs/advanced/faq.md
- docs/advanced/limitations.md
- docs/advanced/migrating-from-dockerfile.md
- docs/deployment.md
- docs/features/k8s.md
- docs/features/multi-platform.md
- docs/install.md
- internal/sbom/sbom.go
- pkg/build/build.go
- pkg/build/gobuild.go
- pkg/commands/resolver.go
- test/main.go
Picks up https://github.com/ko-build/ko/pull/840 and fixes broken links a la https://github.com/ko-build/ko/pull/846
> update docs: fix broken links, align with README

- docs/features/static-assets.md
Fix the FAQ link in [Static Assets](https://ko.build/features/static-assets/).
> Fix link in static-assets.md

- docs/install.md
Reported in https://github.com/ko-build/ko/pull/898/ (thanks @ntns!)
> Fix broken SLSA link

- .github/workflows/registries.yaml
:gift: This leverages OIDC federation to enable presubmit testing against ECR.
/kind feature
> Feature: Add ECR presubmit testing.

- README.md
- docs/community.md
- mkdocs.yml
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Let's have a discussion about the details of the ko community meetings to decide the dates and times.
Fixes #924
> add ko community meeting details

- .github/workflows/build.yaml
- .github/workflows/e2e.yaml
- .github/workflows/image.yaml
- .github/workflows/kind-e2e.yaml
- .github/workflows/modules-integration-test.yaml
- .github/workflows/registries.yaml
- .github/workflows/release.yml
- .github/workflows/sbom.yaml
- .github/workflows/style.yaml
- .github/workflows/test.yaml
- .github/workflows/verify.yaml
- .ko.yaml
- go.mod
- pkg/build/config.go
- pkg/commands/commands.go
- upgrade to use go1.20
- bump go module to require minimum go1.19
> Upgrade to go120

- .github/workflows/release.yml
> fix deprecated attestation name

- .github/workflows/analyze.yaml
- .github/workflows/boilerplate.yaml
- .github/workflows/build.yaml
- .github/workflows/donotsubmit.yaml
- .github/workflows/e2e.yaml
- .github/workflows/image.yaml
- .github/workflows/kind-e2e.yaml
- .github/workflows/modules-integration-test.yaml
- .github/workflows/publish-site.yaml
- .github/workflows/registries.yaml
- .github/workflows/release.yml
- .github/workflows/sbom.yaml
- .github/workflows/stale.yaml
- .github/workflows/style.yaml
- .github/workflows/test.yaml
- .github/workflows/verify.yaml
- use git hash instead of git tag
this is a best practice :)
> use git hash instead of git tag

- pkg/publish/kind/write.go
See: https://github.com/kubernetes-sigs/kind/pull/2957
> Fix kind image loading for MacOS

- mkdocs.yml
> docs: add Lambda and TF pages to sidebar

- docs/advanced/go-packages.md
The [existing docs](https://ko.build/advanced/go-packages/) are pretty slim, so I added an example based on https://github.com/imjasonh/miniko/blob/main/main.go
> include example using go packages

- .github/workflows/release.yml
- docs/install.md
> fix the release workflow and install instructions

- pkg/commands/cache.go
- pkg/commands/config.go
Concurrent writes/reads to the cache might result in partially written files, which we'd like to avoid.
On top of that, we generally don't want builds to fail if something goes wrong with the cache, so now we just log any cache errors and do a fallback.
> Add more locking around on-disk image cache

- docs/index.md
> chore: add capsule as lover
